(function(root){
const companies=[
  {
    "key": "cloudflare",
    "company": "Cloudflare",
    "source": "Greenhouse",
    "board": "cloudflare",
    "industry": "互联网 网络安全 SaaS",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/cloudflare/jobs?content=true",
    "name": "Greenhouse",
    "type": "ats",
    "domain": "boards-api.greenhouse.io",
    "adapter": "greenhouse",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://job-boards.greenhouse.io/cloudflare",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io",
      "cloudflare.com",
      "www.cloudflare.com"
    ],
    "companyName": "Cloudflare",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "stripe",
    "company": "Stripe",
    "source": "Greenhouse",
    "board": "stripe",
    "industry": "金融科技 SaaS 互联网",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/stripe/jobs?content=true",
    "name": "Greenhouse",
    "type": "ats",
    "domain": "boards-api.greenhouse.io",
    "adapter": "greenhouse",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://job-boards.greenhouse.io/stripe",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io",
      "stripe.com",
      "www.stripe.com"
    ],
    "companyName": "Stripe",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "databricks",
    "company": "Databricks",
    "source": "Greenhouse",
    "board": "databricks",
    "industry": "AI 数据 SaaS 企业服务",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/databricks/jobs?content=true",
    "name": "Greenhouse",
    "type": "ats",
    "domain": "boards-api.greenhouse.io",
    "adapter": "greenhouse",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://job-boards.greenhouse.io/databricks",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io",
      "databricks.com",
      "www.databricks.com"
    ],
    "companyName": "Databricks",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "gitlab",
    "company": "GitLab",
    "source": "Greenhouse",
    "board": "gitlab",
    "industry": "SaaS 企业服务 软件",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/gitlab/jobs?content=true",
    "name": "Greenhouse",
    "type": "ats",
    "domain": "boards-api.greenhouse.io",
    "adapter": "greenhouse",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://job-boards.greenhouse.io/gitlab",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io",
      "gitlab.com",
      "www.gitlab.com"
    ],
    "companyName": "GitLab",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "spotify",
    "company": "Spotify",
    "source": "Lever",
    "board": "spotify",
    "industry": "互联网 消费科技 音乐",
    "apiUrl": "https://api.lever.co/v0/postings/spotify?mode=json&limit=500",
    "name": "Lever",
    "type": "ats",
    "domain": "api.lever.co",
    "adapter": "lever",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://jobs.lever.co/spotify",
    "jobHosts": [
      "jobs.lever.co"
    ],
    "companyName": "Spotify",
    "companyType": "外企",
    "atsType": "lever",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "palantir",
    "company": "Palantir",
    "source": "Lever",
    "board": "palantir",
    "industry": "AI 数据 企业服务",
    "apiUrl": "https://api.lever.co/v0/postings/palantir?mode=json&limit=500",
    "name": "Lever",
    "type": "ats",
    "domain": "api.lever.co",
    "adapter": "lever",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://jobs.lever.co/palantir",
    "jobHosts": [
      "jobs.lever.co"
    ],
    "companyName": "Palantir",
    "companyType": "外企",
    "atsType": "lever",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "openai",
    "company": "OpenAI",
    "source": "Ashby",
    "board": "openai",
    "industry": "AI 人工智能",
    "apiUrl": "https://api.ashbyhq.com/posting-api/job-board/openai",
    "name": "Ashby",
    "type": "ats",
    "domain": "api.ashbyhq.com",
    "adapter": "ashby",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://jobs.ashbyhq.com/openai",
    "jobHosts": [
      "jobs.ashbyhq.com"
    ],
    "companyName": "OpenAI",
    "companyType": "外企",
    "atsType": "ashby",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "notion",
    "company": "Notion",
    "source": "Ashby",
    "board": "notion",
    "industry": "SaaS 互联网 企业服务",
    "apiUrl": "https://api.ashbyhq.com/posting-api/job-board/notion",
    "name": "Ashby",
    "type": "ats",
    "domain": "api.ashbyhq.com",
    "adapter": "ashby",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://jobs.ashbyhq.com/notion",
    "jobHosts": [
      "jobs.ashbyhq.com"
    ],
    "companyName": "Notion",
    "companyType": "外企",
    "atsType": "ashby",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "ramp",
    "company": "Ramp",
    "source": "Ashby",
    "board": "ramp",
    "industry": "金融科技 SaaS 企业服务",
    "apiUrl": "https://api.ashbyhq.com/posting-api/job-board/ramp",
    "name": "Ashby",
    "type": "ats",
    "domain": "api.ashbyhq.com",
    "adapter": "ashby",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://jobs.ashbyhq.com/ramp",
    "jobHosts": [
      "jobs.ashbyhq.com"
    ],
    "companyName": "Ramp",
    "companyType": "外企",
    "atsType": "ashby",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "perplexity",
    "company": "Perplexity",
    "source": "Ashby",
    "board": "perplexity",
    "industry": "AI 搜索 互联网",
    "apiUrl": "https://api.ashbyhq.com/posting-api/job-board/perplexity",
    "name": "Ashby",
    "type": "ats",
    "domain": "api.ashbyhq.com",
    "adapter": "ashby",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "careerUrl": "https://jobs.ashbyhq.com/perplexity",
    "jobHosts": [
      "jobs.ashbyhq.com"
    ],
    "companyName": "Perplexity",
    "companyType": "外企",
    "atsType": "ashby",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "epic",
    "company": "Epic Games",
    "name": "Greenhouse",
    "type": "ats",
    "adapter": "greenhouse",
    "board": "epicgames",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "industry": "AI 软件 互联网",
    "domain": "boards-api.greenhouse.io",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/epicgames/jobs?content=true",
    "careerUrl": "https://job-boards.greenhouse.io/epicgames",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io"
    ],
    "companyName": "Epic Games",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "figma",
    "company": "Figma",
    "name": "Greenhouse",
    "type": "ats",
    "adapter": "greenhouse",
    "board": "figma",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "industry": "AI 软件 互联网",
    "domain": "boards-api.greenhouse.io",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/figma/jobs?content=true",
    "careerUrl": "https://job-boards.greenhouse.io/figma",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io"
    ],
    "companyName": "Figma",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "anthropic",
    "company": "Anthropic",
    "name": "Greenhouse",
    "type": "ats",
    "adapter": "greenhouse",
    "board": "anthropic",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "industry": "AI 软件 互联网",
    "domain": "boards-api.greenhouse.io",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/anthropic/jobs?content=true",
    "careerUrl": "https://job-boards.greenhouse.io/anthropic",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io"
    ],
    "companyName": "Anthropic",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "airbnb",
    "company": "Airbnb",
    "name": "Greenhouse",
    "type": "ats",
    "adapter": "greenhouse",
    "board": "airbnb",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "industry": "AI 软件 互联网",
    "domain": "boards-api.greenhouse.io",
    "apiUrl": "https://boards-api.greenhouse.io/v1/boards/airbnb/jobs?content=true",
    "careerUrl": "https://job-boards.greenhouse.io/airbnb",
    "jobHosts": [
      "job-boards.greenhouse.io",
      "boards.greenhouse.io",
      "www.airbnb.com",
      "careers.airbnb.com"
    ],
    "companyName": "Airbnb",
    "companyType": "外企",
    "atsType": "greenhouse",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "linear",
    "company": "Linear",
    "name": "Ashby",
    "type": "ats",
    "adapter": "ashby",
    "board": "linear",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "industry": "AI 软件 互联网",
    "domain": "api.ashbyhq.com",
    "apiUrl": "https://api.ashbyhq.com/posting-api/job-board/linear",
    "careerUrl": "https://jobs.ashbyhq.com/linear",
    "jobHosts": [
      "jobs.ashbyhq.com"
    ],
    "companyName": "Linear",
    "companyType": "外企",
    "atsType": "ashby",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "bosch",
    "company": "Bosch",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "BoschGroup",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "汽车科技 制造业数字化 智能硬件",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/BoschGroup/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/BoschGroup/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "Bosch",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "ikea",
    "company": "Inter IKEA",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "InterIKEAGroup",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "消费科技",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/InterIKEAGroup/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/InterIKEAGroup/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "Inter IKEA",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "ubisoft",
    "company": "Ubisoft",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "Ubisoft2",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "游戏 互联网",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Ubisoft2/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Ubisoft2/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "Ubisoft",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "sgs",
    "company": "SGS",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "SGS",
    "enabled": false,
    "status": "limited",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "咨询 医疗科技",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/SGS/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/SGS/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "SGS",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口正常，但本次 China 列表没有大陆在招职位，不计为 working"
  },
  {
    "key": "aecom",
    "company": "AECOM",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "AECOM2",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "咨询 制造业数字化",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/AECOM2/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/AECOM2/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "AECOM",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "western",
    "company": "Western Digital",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "WesternDigital",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "智能硬件 软件",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/WesternDigital/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/WesternDigital/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "Western Digital",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "sia",
    "company": "Sia",
    "name": "SmartRecruiters",
    "type": "ats",
    "adapter": "smartrecruiters",
    "board": "Sia",
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "industry": "咨询 数据 AI",
    "domain": "api.smartrecruiters.com",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Sia/postings",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Sia/postings",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "companyName": "Sia",
    "companyType": "外企",
    "atsType": "smartrecruiters",
    "reason": "公开接口提供中国大陆职位"
  },
  {
    "key": "tencent",
    "company": "腾讯",
    "name": "腾讯官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "careers.tencent.com",
    "careerUrl": "https://careers.tencent.com/search.html",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "careers.tencent.com"
    ],
    "companyName": "腾讯",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "baidu",
    "company": "百度",
    "name": "百度官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "talent.baidu.com",
    "careerUrl": "https://talent.baidu.com/",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "talent.baidu.com"
    ],
    "companyName": "百度",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "alibaba",
    "company": "阿里巴巴",
    "name": "阿里巴巴官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "talent.alibaba.com",
    "careerUrl": "https://talent.alibaba.com/",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "talent.alibaba.com"
    ],
    "companyName": "阿里巴巴",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "bytedance",
    "company": "字节跳动",
    "name": "字节跳动官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "jobs.bytedance.com",
    "careerUrl": "https://jobs.bytedance.com/experienced/position",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "jobs.bytedance.com"
    ],
    "companyName": "字节跳动",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "netease",
    "company": "网易",
    "name": "网易官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "hr.163.com",
    "careerUrl": "https://hr.163.com/job-list.html",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "hr.163.com"
    ],
    "companyName": "网易",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "xiaomi",
    "company": "小米",
    "name": "小米官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "hr.xiaomi.com",
    "careerUrl": "https://hr.xiaomi.com/",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "hr.xiaomi.com"
    ],
    "companyName": "小米",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "mihoyo",
    "company": "米哈游",
    "name": "米哈游官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "join.mihoyo.com",
    "careerUrl": "https://join.mihoyo.com/",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "join.mihoyo.com"
    ],
    "companyName": "米哈游",
    "companyType": "民企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "jetbrains",
    "company": "JetBrains",
    "name": "JetBrains官网",
    "type": "company_career",
    "adapter": "generic-career",
    "domain": "www.jetbrains.com",
    "careerUrl": "https://www.jetbrains.com/careers/jobs/",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 3,
    "jobHosts": [
      "www.jetbrains.com"
    ],
    "companyName": "JetBrains",
    "companyType": "外企",
    "atsType": "generic-career",
    "reason": "尚未取得大陆职位或页面需要 JavaScript"
  },
  {
    "key": "company-0",
    "companyName": "中国移动",
    "company": "中国移动",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.10086.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国移动官网",
    "type": "company_career",
    "domain": "job.10086.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.10086.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-1",
    "companyName": "中国电信",
    "company": "中国电信",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.chinatelecom.com.cn/wt/TELE/web/index",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国电信官网",
    "type": "company_career",
    "domain": "job.chinatelecom.com.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.chinatelecom.com.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-3",
    "companyName": "国家电网",
    "company": "国家电网",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://zhaopin.sgcc.com.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "国家电网官网",
    "type": "company_career",
    "domain": "zhaopin.sgcc.com.cn",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "zhaopin.sgcc.com.cn"
    ],
    "reason": "HTTP_412"
  },
  {
    "key": "company-4",
    "companyName": "南方电网",
    "company": "南方电网",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://zhaopin.csg.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "南方电网官网",
    "type": "company_career",
    "domain": "zhaopin.csg.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "zhaopin.csg.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-5",
    "companyName": "国家能源集团",
    "company": "国家能源集团",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://zhaopin.chnenergy.com.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "国家能源集团官网",
    "type": "company_career",
    "domain": "zhaopin.chnenergy.com.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "zhaopin.chnenergy.com.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-6",
    "companyName": "中国石化",
    "company": "中国石化",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.sinopec.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国石化官网",
    "type": "company_career",
    "domain": "job.sinopec.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.sinopec.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-7",
    "companyName": "中国石油",
    "company": "中国石油",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://zhaopin.cnpc.com.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国石油官网",
    "type": "company_career",
    "domain": "zhaopin.cnpc.com.cn",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "zhaopin.cnpc.com.cn"
    ],
    "reason": "HTTP_412"
  },
  {
    "key": "company-8",
    "companyName": "中国华能",
    "company": "中国华能",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://zhaopin.chng.com.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国华能官网",
    "type": "company_career",
    "domain": "zhaopin.chng.com.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "zhaopin.chng.com.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-14",
    "companyName": "中国核工业",
    "company": "中国核工业",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://cnnc.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "中国核工业官网",
    "type": "company_career",
    "domain": "cnnc.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "cnnc.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-17",
    "companyName": "中国电建",
    "company": "中国电建",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://zhaopin.powerchina.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国电建官网",
    "type": "company_career",
    "domain": "zhaopin.powerchina.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "zhaopin.powerchina.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-18",
    "companyName": "中国建筑",
    "company": "中国建筑",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://cscec.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "中国建筑官网",
    "type": "company_career",
    "domain": "cscec.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "cscec.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-19",
    "companyName": "中国交建",
    "company": "中国交建",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://ccccltd.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "中国交建官网",
    "type": "company_career",
    "domain": "ccccltd.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "ccccltd.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-24",
    "companyName": "中国南方航空",
    "company": "中国南方航空",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.csair.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国南方航空官网",
    "type": "company_career",
    "domain": "job.csair.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.csair.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-25",
    "companyName": "中国东方航空",
    "company": "中国东方航空",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.ceair.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中国东方航空官网",
    "type": "company_career",
    "domain": "job.ceair.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.ceair.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-28",
    "companyName": "招商局集团",
    "company": "招商局集团",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://cmhk.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "招商局集团官网",
    "type": "company_career",
    "domain": "cmhk.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "cmhk.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-32",
    "companyName": "工商银行",
    "company": "工商银行",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.icbc.com.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "工商银行官网",
    "type": "company_career",
    "domain": "job.icbc.com.cn",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.icbc.com.cn"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-33",
    "companyName": "建设银行",
    "company": "建设银行",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.ccb.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "建设银行官网",
    "type": "company_career",
    "domain": "job.ccb.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.ccb.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-36",
    "companyName": "农业银行",
    "company": "农业银行",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://career.abchina.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "农业银行官网",
    "type": "company_career",
    "domain": "career.abchina.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "career.abchina.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-37",
    "companyName": "交通银行",
    "company": "交通银行",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://job.bankcomm.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "交通银行官网",
    "type": "company_career",
    "domain": "job.bankcomm.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "job.bankcomm.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-38",
    "companyName": "中国人寿",
    "company": "中国人寿",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://chinalife.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "中国人寿官网",
    "type": "company_career",
    "domain": "chinalife.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "chinalife.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-40",
    "companyName": "中国人保",
    "company": "中国人保",
    "companyType": "央企",
    "industry": "能源 电力 通信 金融 交通 制造 工程",
    "careerUrl": "https://picc.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "中国人保官网",
    "type": "company_career",
    "domain": "picc.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "picc.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-42",
    "companyName": "北京银行",
    "company": "北京银行",
    "companyType": "国企",
    "industry": "银行 金融 制造 交通",
    "careerUrl": "https://bankofbeijing.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "北京银行官网",
    "type": "company_career",
    "domain": "bankofbeijing.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 1,
    "jobHosts": [
      "bankofbeijing.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-44",
    "companyName": "华为",
    "company": "华为",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://career.huawei.com/cn/social-recruitment",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "华为官网",
    "type": "company_career",
    "domain": "career.huawei.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "career.huawei.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-46",
    "companyName": "联想",
    "company": "联想",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://talent.lenovo.com.cn/position",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "联想官网",
    "type": "company_career",
    "domain": "talent.lenovo.com.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "talent.lenovo.com.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-47",
    "companyName": "比亚迪",
    "company": "比亚迪",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://job.byd.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "比亚迪官网",
    "type": "company_career",
    "domain": "job.byd.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "job.byd.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-49",
    "companyName": "美团",
    "company": "美团",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://zhaopin.meituan.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "美团官网",
    "type": "company_career",
    "domain": "zhaopin.meituan.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "zhaopin.meituan.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-50",
    "companyName": "京东",
    "company": "京东",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://zhaopin.jd.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "京东官网",
    "type": "company_career",
    "domain": "zhaopin.jd.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "zhaopin.jd.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-51",
    "companyName": "拼多多",
    "company": "拼多多",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://careers.pinduoduo.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "拼多多官网",
    "type": "company_career",
    "domain": "careers.pinduoduo.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.pinduoduo.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-52",
    "companyName": "携程",
    "company": "携程",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://careers.ctrip.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "携程官网",
    "type": "company_career",
    "domain": "careers.ctrip.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.ctrip.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-53",
    "companyName": "快手",
    "company": "快手",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://zhaopin.kuaishou.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "快手官网",
    "type": "company_career",
    "domain": "zhaopin.kuaishou.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "zhaopin.kuaishou.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-54",
    "companyName": "滴滴",
    "company": "滴滴",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://talent.didiglobal.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "滴滴官网",
    "type": "company_career",
    "domain": "talent.didiglobal.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "talent.didiglobal.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-55",
    "companyName": "哔哩哔哩",
    "company": "哔哩哔哩",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://jobs.bilibili.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "哔哩哔哩官网",
    "type": "company_career",
    "domain": "jobs.bilibili.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.bilibili.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-62",
    "companyName": "OPPO",
    "company": "OPPO",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://careers.oppo.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "OPPO官网",
    "type": "company_career",
    "domain": "careers.oppo.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.oppo.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-63",
    "companyName": "vivo",
    "company": "vivo",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://hr.vivo.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "vivo官网",
    "type": "company_career",
    "domain": "hr.vivo.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "hr.vivo.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-64",
    "companyName": "荣耀",
    "company": "荣耀",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://career.honor.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "荣耀官网",
    "type": "company_career",
    "domain": "career.honor.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "career.honor.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-66",
    "companyName": "大华",
    "company": "大华",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://dahua.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "大华官网",
    "type": "company_career",
    "domain": "dahua.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "dahua.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-67",
    "companyName": "中兴通讯",
    "company": "中兴通讯",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://job.zte.com.cn/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "中兴通讯官网",
    "type": "company_career",
    "domain": "job.zte.com.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "job.zte.com.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-69",
    "companyName": "格力",
    "company": "格力",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://job.gree.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "格力官网",
    "type": "company_career",
    "domain": "job.gree.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "job.gree.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-70",
    "companyName": "美的",
    "company": "美的",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://careers.midea.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "美的官网",
    "type": "company_career",
    "domain": "careers.midea.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.midea.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-72",
    "companyName": "吉利",
    "company": "吉利",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://job.geely.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "吉利官网",
    "type": "company_career",
    "domain": "job.geely.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "job.geely.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-74",
    "companyName": "宁德时代",
    "company": "宁德时代",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://careers.catl.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "宁德时代官网",
    "type": "company_career",
    "domain": "careers.catl.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.catl.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-76",
    "companyName": "招商银行",
    "company": "招商银行",
    "companyType": "国企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://career.cmbchina.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "招商银行官网",
    "type": "company_career",
    "domain": "career.cmbchina.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "career.cmbchina.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-77",
    "companyName": "平安集团",
    "company": "平安集团",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://talent.pingan.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "平安集团官网",
    "type": "company_career",
    "domain": "talent.pingan.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "talent.pingan.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-79",
    "companyName": "迈瑞医疗",
    "company": "迈瑞医疗",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://mindray.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "迈瑞医疗官网",
    "type": "company_career",
    "domain": "mindray.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "mindray.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-80",
    "companyName": "药明康德",
    "company": "药明康德",
    "companyType": "民企",
    "industry": "科技 互联网 软件 AI 汽车 新能源 消费",
    "careerUrl": "https://wuxiapptec.zhiye.com/",
    "atsType": "北森",
    "adapter": "generic-career",
    "name": "药明康德官网",
    "type": "company_career",
    "domain": "wuxiapptec.zhiye.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "wuxiapptec.zhiye.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-81",
    "companyName": "西门子",
    "company": "西门子",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.siemens.com.cn/siemens/position/index",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "西门子官网",
    "type": "company_career",
    "domain": "jobs.siemens.com.cn",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.siemens.com.cn"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-82",
    "companyName": "SAP",
    "company": "SAP",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.sap.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "SAP官网",
    "type": "company_career",
    "domain": "jobs.sap.com",
    "enabled": false,
    "status": "blocked",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.sap.com"
    ],
    "reason": "公开访问受限，停止"
  },
  {
    "key": "company-83",
    "companyName": "Microsoft",
    "company": "Microsoft",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.microsoft.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Microsoft官网",
    "type": "company_career",
    "domain": "careers.microsoft.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.microsoft.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-84",
    "companyName": "Apple",
    "company": "Apple",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.apple.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Apple官网",
    "type": "company_career",
    "domain": "jobs.apple.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.apple.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-85",
    "companyName": "Oracle",
    "company": "Oracle",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.oracle.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Oracle官网",
    "type": "company_career",
    "domain": "careers.oracle.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.oracle.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-86",
    "companyName": "Amazon",
    "company": "Amazon",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.amazon.jobs/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Amazon官网",
    "type": "company_career",
    "domain": "www.amazon.jobs",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.amazon.jobs"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-88",
    "companyName": "IBM",
    "company": "IBM",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.ibm.com/careers/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "IBM官网",
    "type": "company_career",
    "domain": "www.ibm.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.ibm.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-89",
    "companyName": "NVIDIA",
    "company": "NVIDIA",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite",
    "atsType": "Workday",
    "adapter": "generic-career",
    "name": "NVIDIA官网",
    "type": "company_career",
    "domain": "nvidia.wd5.myworkdayjobs.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "nvidia.wd5.myworkdayjobs.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-90",
    "companyName": "Google",
    "company": "Google",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.google.com/about/careers/applications/jobs/results/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Google官网",
    "type": "company_career",
    "domain": "www.google.com",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.google.com"
    ],
    "reason": "TypeError"
  },
  {
    "key": "company-91",
    "companyName": "AMD",
    "company": "AMD",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.amd.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "AMD官网",
    "type": "company_career",
    "domain": "careers.amd.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.amd.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-92",
    "companyName": "Qualcomm",
    "company": "Qualcomm",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.qualcomm.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Qualcomm官网",
    "type": "company_career",
    "domain": "careers.qualcomm.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.qualcomm.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-93",
    "companyName": "Intel",
    "company": "Intel",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.intel.com/",
    "atsType": "Workday",
    "adapter": "generic-career",
    "name": "Intel官网",
    "type": "company_career",
    "domain": "jobs.intel.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.intel.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-94",
    "companyName": "Tesla",
    "company": "Tesla",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.tesla.com/careers/search/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Tesla官网",
    "type": "company_career",
    "domain": "www.tesla.com",
    "enabled": false,
    "status": "blocked",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.tesla.com"
    ],
    "reason": "公开访问受限，停止"
  },
  {
    "key": "company-95",
    "companyName": "Cisco",
    "company": "Cisco",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.cisco.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Cisco官网",
    "type": "company_career",
    "domain": "jobs.cisco.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.cisco.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-96",
    "companyName": "Bayer",
    "company": "Bayer",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.bayer.com/",
    "atsType": "SAP SuccessFactors",
    "adapter": "generic-career",
    "name": "Bayer官网",
    "type": "company_career",
    "domain": "jobs.bayer.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.bayer.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-97",
    "companyName": "Schneider Electric",
    "company": "Schneider Electric",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.se.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Schneider Electric官网",
    "type": "company_career",
    "domain": "careers.se.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.se.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-98",
    "companyName": "Accenture",
    "company": "Accenture",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.accenture.com/us-en/careers",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Accenture官网",
    "type": "company_career",
    "domain": "www.accenture.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.accenture.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-99",
    "companyName": "Honeywell",
    "company": "Honeywell",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.honeywell.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Honeywell官网",
    "type": "company_career",
    "domain": "careers.honeywell.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.honeywell.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-100",
    "companyName": "BASF",
    "company": "BASF",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://basf.jobs/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "BASF官网",
    "type": "company_career",
    "domain": "basf.jobs",
    "enabled": false,
    "status": "unavailable",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "basf.jobs"
    ],
    "reason": "TimeoutError"
  },
  {
    "key": "company-101",
    "companyName": "PwC",
    "company": "PwC",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.pwccn.com/en/careers.html",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "PwC官网",
    "type": "company_career",
    "domain": "www.pwccn.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.pwccn.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-102",
    "companyName": "KPMG",
    "company": "KPMG",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://kpmg.com/cn/en/home/careers.html",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "KPMG官网",
    "type": "company_career",
    "domain": "kpmg.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "kpmg.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-103",
    "companyName": "EY",
    "company": "EY",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.ey.com/",
    "atsType": "successfactors",
    "adapter": "successfactors-html",
    "name": "EY官网",
    "type": "company_career",
    "domain": "careers.ey.com",
    "enabled": true,
    "status": "working",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.ey.com"
    ],
    "reason": "实际公开 HTML 提供真实职位链接和城市",
    "searchUrls": [
      "https://careers.ey.com/ey/search/?createNewAlert=false&q=&locationsearch=Shanghai&optionsFacetsDD_country=CN&optionsFacetsDD_customfield1=&locale=en_US",
      "https://careers.ey.com/ey/search/?createNewAlert=false&q=&locationsearch=Beijing&optionsFacetsDD_country=CN&optionsFacetsDD_customfield1=&locale=en_US",
      "https://careers.ey.com/ey/search/?createNewAlert=false&q=&locationsearch=Shenzhen&optionsFacetsDD_country=CN&optionsFacetsDD_customfield1=&locale=en_US"
    ]
  },
  {
    "key": "company-104",
    "companyName": "Deloitte",
    "company": "Deloitte",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://jobs.deloitte.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Deloitte官网",
    "type": "company_career",
    "domain": "jobs.deloitte.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "jobs.deloitte.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-105",
    "companyName": "Nestlé",
    "company": "Nestlé",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.nestle.com/jobs",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Nestlé官网",
    "type": "company_career",
    "domain": "www.nestle.com",
    "enabled": false,
    "status": "blocked",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.nestle.com"
    ],
    "reason": "公开访问受限，停止"
  },
  {
    "key": "company-106",
    "companyName": "Unilever",
    "company": "Unilever",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.unilever.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Unilever官网",
    "type": "company_career",
    "domain": "careers.unilever.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.unilever.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-107",
    "companyName": "Roche",
    "company": "Roche",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.roche.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Roche官网",
    "type": "company_career",
    "domain": "careers.roche.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.roche.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-108",
    "companyName": "P&G",
    "company": "P&G",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.pgcareers.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "P&G官网",
    "type": "company_career",
    "domain": "www.pgcareers.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.pgcareers.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-109",
    "companyName": "Novartis",
    "company": "Novartis",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://www.novartis.com/careers/career-search",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "Novartis官网",
    "type": "company_career",
    "domain": "www.novartis.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "www.novartis.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-110",
    "companyName": "L’Oréal",
    "company": "L’Oréal",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.loreal.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "L’Oréal官网",
    "type": "company_career",
    "domain": "careers.loreal.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.loreal.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "company-111",
    "companyName": "AstraZeneca",
    "company": "AstraZeneca",
    "companyType": "外企",
    "industry": "科技 软件 芯片 制造 咨询 医药 汽车 工业",
    "careerUrl": "https://careers.astrazeneca.com/",
    "atsType": "generic",
    "adapter": "generic-career",
    "name": "AstraZeneca官网",
    "type": "company_career",
    "domain": "careers.astrazeneca.com",
    "enabled": false,
    "status": "limited",
    "method": "public_html",
    "lastChecked": "2026-10-05",
    "priority": 2,
    "jobHosts": [
      "careers.astrazeneca.com"
    ],
    "reason": "页面可访问，待确认真实职位URL与大陆地点"
  },
  {
    "key": "vitol",
    "companyName": "Vitol",
    "company": "Vitol",
    "companyType": "外企",
    "industry": "能源 金融 数据",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Vitol/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "Vitol",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Vitol/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "nielseniq",
    "companyName": "NielsenIQ",
    "company": "NielsenIQ",
    "companyType": "外企",
    "industry": "数据 消费科技 咨询",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/NielsenIQ/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "NielsenIQ",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/NielsenIQ/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "ldc",
    "companyName": "Louis Dreyfus Company",
    "company": "Louis Dreyfus Company",
    "companyType": "外企",
    "industry": "消费 制造 金融",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/LouisDreyfusCompany/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "LouisDreyfusCompany",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/LouisDreyfusCompany/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "eurofins",
    "companyName": "Eurofins",
    "company": "Eurofins",
    "companyType": "外企",
    "industry": "医疗科技 检测",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Eurofins/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "Eurofins",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Eurofins/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "roland",
    "companyName": "Roland Berger",
    "company": "Roland Berger",
    "companyType": "外企",
    "industry": "咨询 数据",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/RolandBerger/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "RolandBerger",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/RolandBerger/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "beumer",
    "companyName": "BEUMER Group",
    "company": "BEUMER Group",
    "companyType": "外企",
    "industry": "制造业数字化 软件",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/BEUMERGroup1/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "BEUMERGroup1",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/BEUMERGroup1/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "expeditors",
    "companyName": "Expeditors",
    "company": "Expeditors",
    "companyType": "外企",
    "industry": "物流 软件",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Expeditors/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "Expeditors",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Expeditors/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "thirdbridge",
    "companyName": "Third Bridge",
    "company": "Third Bridge",
    "companyType": "外企",
    "industry": "咨询 软件 数据",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/ThirdBridge/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "ThirdBridge",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/ThirdBridge/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "aumovio",
    "companyName": "AUMOVIO",
    "company": "AUMOVIO",
    "companyType": "外企",
    "industry": "汽车科技 软件 算法",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Aumovio/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "Aumovio",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Aumovio/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "avery",
    "companyName": "Avery Dennison",
    "company": "Avery Dennison",
    "companyType": "外企",
    "industry": "制造 消费科技",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/AveryDennison/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "AveryDennison",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/AveryDennison/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "contitech",
    "companyName": "Continental ContiTech",
    "company": "Continental ContiTech",
    "companyType": "外企",
    "industry": "汽车科技 制造",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/ContinentalGroupSectorContiTech/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "ContinentalGroupSectorContiTech",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/ContinentalGroupSectorContiTech/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  },
  {
    "key": "wabtec",
    "companyName": "Wabtec",
    "company": "Wabtec",
    "companyType": "外企",
    "industry": "交通 软件 工业",
    "careerUrl": "https://api.smartrecruiters.com/v1/companies/Wabtec/postings",
    "atsType": "smartrecruiters",
    "adapter": "smartrecruiters",
    "name": "SmartRecruiters",
    "type": "ats",
    "board": "Wabtec",
    "apiUrl": "https://api.smartrecruiters.com/v1/companies/Wabtec/postings",
    "domain": "api.smartrecruiters.com",
    "jobHosts": [
      "jobs.smartrecruiters.com"
    ],
    "enabled": true,
    "status": "working",
    "method": "official_public_api",
    "lastChecked": "2026-10-05",
    "priority": 2
  }
];
root.CompanySources=Object.freeze(companies.map(Object.freeze));root.PublicSources=Object.freeze(companies.map(Object.freeze));if(typeof module!=="undefined")module.exports={companies:root.CompanySources,sources:root.PublicSources};
})(typeof window==="undefined"?globalThis:window);
