const {test}=require('node:test'),assert=require('node:assert/strict');require('../js/job-keyword-aliases.js');const core=require('../js/job-core.js');
const base={id:'test:1',title:'BI Analyst',company:'Test',companyType:'外企',sourceType:'ats',industry:'软件',location:'浦东',description:'SQL',url:'https://company.invalid/jobs/1'};
test('官方池岗位别名、地区别名、行业加分和企业类型筛选',()=>{for(const [role,title,city,loc] of [['数据分析师','BI Analyst','上海','浦东'],['产品经理','Product Manager','上海','闵行'],['软件工程师','Software Engineer','北京','海淀'],['算法工程师','Machine Learning Engineer','深圳','南山区']])assert.equal(core.shortlist([{...base,title,location:loc}],{role,city},{}).length,1);assert.equal(core.shortlist([{...base,location:'Suzhou, China'}],{role:'数据分析师',city:'上海'},{}).length,0);assert.equal(core.filter([base],{companyType:'国央企'}).length,0);assert.equal(core.filter([{...base,companyType:'国企'}],{companyType:'国央企'}).length,1);assert.equal(core.shortlist([{...base,title:'电话销售'}],{exclude:'销售'},{}).length,0);assert.equal(core.shortlist([{...base,title:'销售数据分析师'}],{exclude:'销售'},{}).length,1);});
test('大陆限定不接受美国、港澳台、模糊全球远程',async()=>{const {mainlandLocation}=await import('../sources/mainland.mjs');for(const loc of ['Shanghai, China','北京','Shenzhen','Remote China'])assert.equal(mainlandLocation(loc),true);for(const loc of ['New York','Hong Kong, China','Taipei','Remote worldwide','APAC','未公开'])assert.equal(mainlandLocation(loc),false);});
test('持久职位池不接受简历/画像，仅公开数据且大小有界',async()=>{const {CompanyJobPool}=await import('../sources/company-pool.mjs');const records=new Map();const pool=new CompanyJobPool({storage:{async list(){return records;},async put(k,v){records.set(k,v);}}});const post=body=>pool.fetch(new Request('https://pool.internal/update',{method:'POST',body:JSON.stringify(body)}));assert.equal((await post({records:[{key:'test',jobs:[],checkedAt:1,expiresAt:2,status:'working',failures:0,retryAt:0,resumeText:'private'}]})).status,400);assert.equal(records.size,0);assert.equal((await post({records:[{key:'test',jobs:[base],checkedAt:1,expiresAt:2,status:'working',failures:0,retryAt:0}]})).status,200);assert.equal((await(await pool.fetch(new Request('https://pool.internal/snapshot'))).json()).records[0].jobs[0].title,'BI Analyst');});
test('公司级4小时缓存与关键词无关，真实URL来自详情，失败隔离、不发送个人数据',async()=>{const {collectOfficialJobs}=await import('../sources/official-pool-service.mjs');const registry=[{key:'pool-test',companyName:'Test',companyType:'外企',industry:'软件',name:'SmartRecruiters',type:'ats',adapter:'smartrecruiters',enabled:true,status:'working',priority:2,apiUrl:'https://api.smartrecruiters.com/v1/companies/Test/postings',jobHosts:['jobs.smartrecruiters.com']},{key:'pool-bad',companyName:'Bad',companyType:'民企',name:'Bad',type:'ats',adapter:'greenhouse',enabled:true,status:'working',apiUrl:'https://bad.invalid/jobs',priority:1}];let calls=0;const fetcher=async(url,opts)=>{calls++;assert.equal(opts.headers.Authorization,undefined);assert.equal(opts.body,undefined);if(url.includes('bad.invalid'))return new Response('denied',{status:403});if(url.includes('offset='))return Response.json({totalFound:1,content:[{name:'BI Analyst',visibility:'PUBLIC',ref:'https://api.smartrecruiters.com/v1/companies/Test/postings/1',location:{city:'Shanghai',country:'cn'},company:{name:'Test'}}]});return Response.json({name:'BI Analyst',visibility:'PUBLIC',active:true,postingUrl:'https://jobs.smartrecruiters.com/Test/real',location:{city:'Shanghai'},jobAd:{sections:{description:{text:'SQL'}}}});};const p={role:'数据分析师',city:'上海'},a=await collectOfficialJobs(p,{registry,fetcher,now:10000000});assert.equal(a.jobs[0].url,'https://jobs.smartrecruiters.com/Test/real');assert.equal(a.sourceReports.find(s=>s.key==='pool-bad').status,'blocked');const b=await collectOfficialJobs({role:'产品经理',city:'上海'},{registry,fetcher,now:10000001});assert.equal(b.jobs.length,0);assert.equal(calls,3);assert.equal(b.poolTotal,1);assert.equal(a.searchCalls,0);});
test('SuccessFactors公开HTML只保留大陆职位与实际href',async()=>{const {parse}=await import('../sources/adapters/successfactors-html.mjs');const row=(loc,url)=>'<tr class="data-row"><a href="'+url+'" class="jobTitle-link">Data Analyst</a><span class="jobLocation">'+loc+'</span></tr>';const s={key:'ey-test',name:'EY官网',companyName:'EY',companyType:'外企',type:'company_career',jobHosts:['careers.ey.com']};const j=parse(s,row('Shanghai, CN','/ey/job/actual/1/')+row('Hong Kong, CN','/ey/job/actual/2/'),'https://careers.ey.com/');assert.equal(j.length,1);assert.equal(j[0].url,'https://careers.ey.com/ey/job/actual/1/');});

test('明确未知城市也不能因country=China混入指定城市',async()=>{const {collectOfficialJobs}=await import('../sources/official-pool-service.mjs');const source={key:'strict-city',companyName:'T',name:'T',type:'company_career',adapter:'generic-career',enabled:true,status:'working',priority:1,careerUrl:'https://t.invalid/jobs',jobHosts:['t.invalid']};const html='<script type="application/ld+json">'+JSON.stringify({'@type':'JobPosting',title:'Software Engineer',url:'https://t.invalid/job/1',description:'Java',jobLocation:{address:{addressLocality:'Wuhu, China'}}})+'</script>';const r=await collectOfficialJobs({role:'软件工程师',city:'北京'},{registry:[source],fetcher:async()=>new Response(html),now:20000000});assert.equal(r.poolTotal,1);assert.equal(r.jobs.length,0);});

test('JD未公开时不能展示模型猜测或错引用其他岗位的要求',async()=>{const {validateMatches}=await import('../ai/job-matching.mjs');const result=validateMatches({matches:[{id:'no-jd',matchScore:40,confidence:'高',matchReasons:['另一家公司要求机器学习'],gaps:['没有Python'],recommendation:'不能申请',resumeTips:['增加虚构Python项目']}]},[{id:'no-jd',description:'未公开',searchSummaryOnly:true}]);const m=result.matches[0];assert.equal(m.confidence,'低');assert.ok(m.gaps[0].includes('信息不足'));assert.ok(!JSON.stringify(m).includes('Python'));assert.ok(!JSON.stringify(m).includes('另一家'));});
