const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
require('../js/analysis-contract.js');const c=require('../js/optimization-contract.js');const sample=require('./analysis-sample.cjs');
const body=()=>({resumeText:sample.resumeText,analysis:sample.analysis,targetRole:'数据分析师',jd:'岗位职责：使用 SQL、Excel 制作业务报表，整理零售数据。要求本科，具备 SQL 和 Excel 实践，Python 加分。',focuses:['提升 JD 匹配度','优化工作经历表达','增强 ATS 关键词'],extraRequirements:'保留教育经历'});
const result=()=>({jdSummary:'需要 SQL、Excel 报表和数据整理能力，Python 为加分项。',matchScore:85,matchedStrengths:['原文有 SQL、Excel 报表实践'],gaps:['Python 暂无证据'],importantKeywords:['SQL','Excel','报表'],optimizationSummary:['突出报表职责'],optimizedProfile:'具备零售行业数据整理经验。',optimizedSkills:['SQL','Excel'],optimizedExperiences:[{company:'星河测试企业',title:'数据分析师',original:'使用 SQL、Excel 制作销售报表。负责零售行业数据整理。',optimized:'负责零售行业数据整理，使用 SQL、Excel 制作销售报表。',reason:'突出与 JD 的报表职责关联，未增加事实。'}],optimizedProjects:[],missingEvidence:['Python 暂无原文证据'],suggestedQuestions:['如果确实使用过 Python，可以补充真实经历。'],fullOptimizedResume:sample.resumeText});
test('简单strict schema所有字段必填、经历对象不允许额外字段',()=>{assert.equal(c.schema.additionalProperties,false);assert.deepEqual(c.schema.required,Object.keys(c.schema.properties));for(const name of ['optimizedExperiences','optimizedProjects'])assert.equal(c.schema.properties[name].items.additionalProperties,false);});
test('完整/极短/英文JD有效，超过12000拒绝，空JD/角色/简历不调用',()=>{assert.equal(c.input(body()).targetRole,'数据分析师');for(const jd of ['数据分析','Use SQL and Excel for retail reporting.'])assert.equal(c.input({...body(),jd}).jd,jd);assert.throws(()=>c.input({...body(),jd:'x'.repeat(12001)}),{code:'INPUT_TOO_LONG'});assert.equal(c.input({...body(),jd:'x'.repeat(12000)}).jd.length,12000);for(const key of ['jd','targetRole','resumeText'])assert.throws(()=>c.input({...body(),[key]:''}),{code:'EMPTY_INPUT'});});
test('归一化安全差异，但不掩盖无法使用的空结果或无效评分',()=>{const r=result();r.gaps='待补充';r.matchScore='85%';assert.deepEqual(c.validate(c.normalize(r)).gaps,['待补充']);assert.throws(()=>c.validate(c.normalize({})),{code:'INVALID_SCHEMA'});assert.throws(()=>c.validate(c.normalize({...result(),matchScore:120})),{code:'INVALID_SCHEMA'});});
test('真实技能缺口不写回简历；虚构数字与成果回退原文；不接受伪原文',()=>{let r=result();r.optimizedSkills.push('Python');r.optimizedExperiences[0].optimized='通过 Python 使转化提升35%，管理20人。';r.optimizedProfile='管理20人的 Python 团队。';r.fullOptimizedResume='虚构学校和35%';r=c.safeguard(c.validate(c.normalize(r)),sample.resumeText);assert.deepEqual(r.optimizedSkills,['SQL','Excel']);assert.equal(r.optimizedExperiences[0].optimized,r.optimizedExperiences[0].original);assert.doesNotMatch(r.fullOptimizedResume,/Python|35%|20人|虚构学校/);assert.match(r.fullOptimizedResume,/测试大学/);r=result();r.optimizedExperiences[0].original='虚构原文';assert.equal(c.safeguard(r,sample.resumeText).optimizedExperiences.length,0);});
test('无项目时虚构项目丢弃；有项目只重述真实原文并保留真实数字',()=>{const p={name:'报表整理项目',original:'报表整理项目：使用 SQL 整理报表，共处理 12 份。',optimized:'报表整理项目：使用 SQL 完成 12 份报表整理。',reason:'使动作清晰，不添加结果。'};let r=result();r.optimizedProjects=[p];assert.equal(c.safeguard(r,sample.resumeText).optimizedProjects.length,0);r=result();r.optimizedProjects=[p];const kept=c.safeguard(r,sample.resumeText+'\n'+p.original);assert.equal(kept.optimizedProjects.length,1);assert.match(kept.fullOptimizedResume,/12 份报表整理/);});
test('高匹配结果和全文保留所有时间、公司、真实职位及教育',()=>{const r=c.safeguard(result(),sample.resumeText);assert.equal(r.matchScore,85);for(const value of ['2021.01-2024.01','星河测试企业','数据分析师','2017-2021','测试大学','统计学','本科'])assert.ok(r.fullOptimizedResume.includes(value));assert.doesNotMatch(r.fullOptimizedResume,/Python/);});
const req=payload=>new Request('https://unit.invalid/api/resume/optimize',{method:'POST',headers:{Origin:'http://127.0.0.1:4173','Content-Type':'application/json'},body:JSON.stringify(payload)});
test('优化接口一次HTTP模型调用、thinking关闭、strict JSON、无搜索、预检不调用',async()=>{const {handleOptimization}=await import('../ai/optimization-handler.mjs');const {resetLimitsForTests}=await import('../ai/handler.mjs');resetLimitsForTests();let calls=0;const fetcher=async(url,options)=>{calls++;assert.equal(url,'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions');const b=JSON.parse(options.body);assert.equal(b.model,'qwen3.8-flash');assert.equal(b.enable_thinking,false);assert.equal(b.response_format.json_schema.strict,true);assert.equal(b.messages.length,2);return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(result())}}]});};const env={AI_API_KEY:'unit-only-fixture',AI_BASE_URL:'https://unit.cn-beijing.maas.aliyuncs.com/compatible-mode/v1'};let response=await handleOptimization(req(body()),env,fetcher);assert.equal(response.status,200);assert.equal(calls,1);assert.equal((await response.json()).mode,'live');response=await handleOptimization(new Request('https://unit.invalid/api/resume/optimize',{method:'OPTIONS',headers:{Origin:'http://127.0.0.1:4173'}}),env,fetcher);assert.equal(response.status,204);assert.equal(calls,1);assert.equal(response.headers.get('Access-Control-Allow-Headers'),'Content-Type');});
test('网络/JSON/Schema异常不会自动重试；日志不包含内容或密钥',async()=>{const {handleOptimization}=await import('../ai/optimization-handler.mjs');const {resetLimitsForTests}=await import('../ai/handler.mjs');for(const [reply,expected]of [[()=>{throw new TypeError('fetch failed');},'UPSTREAM_NETWORK'],[()=>Response.json({choices:[{finish_reason:'stop',message:{content:'broken'}}]}),'INVALID_JSON'],[()=>Response.json({choices:[{finish_reason:'stop',message:{content:'{}'}}]}),'INVALID_SCHEMA']]){resetLimitsForTests();let calls=0;const logs=[];const old=console.info;console.info=s=>logs.push(s);let response;try{response=await handleOptimization(req(body()),{AI_API_KEY:'unit-only-fixture',AI_BASE_URL:'https://dashscope.aliyuncs.com/compatible-mode/v1'},async()=>{calls++;return reply();});}finally{console.info=old;}assert.equal(calls,1);assert.equal((await response.json()).error.code,expected);assert.doesNotMatch(logs.join(''),/unit-only-fixture|星河测试企业|制作销售报表/);}});
test('旧搜索路由默认关闭，新接口路由可预检且缺配置友好失败',async()=>{const {default:worker}=await import('../worker/index.mjs');assert.equal((await worker.fetch(new Request('https://unit.invalid/api/jobs/search'),{})).status,403);assert.equal((await worker.fetch(req(body()),{})).status,503);});
test('正常页面只有新流程，推荐方向能进入第三步；复制及重新优化按钮保留输入',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('js/app.js','utf8');assert.doesNotMatch(html,/发现匹配岗位|搜索匹配岗位|真实岗位|岗位来源|招聘平台|Greenhouse|Lever|Ashby|WebSearch/);assert.doesNotMatch(html,/js\/(?:jobs-provider|public-jobs-provider|websearch-core)\.js/);assert.match(app,/showStep\(3\);\s*\$\('target-jd'\)\.focus/);assert.match(app,/navigator.clipboard.writeText\(state.optimization.fullOptimizedResume\)/);assert.match(app,/'#reoptimize'/);assert.doesNotMatch(app,/providers.jobProvider.search/);});

test('实测回归：报表不能推断运营协作，说明不声称已经补写，日期子串不能当年限证据',()=>{const r=result();r.optimizedExperiences[0].optimized='负责报表，对接运营团队，主导跨部门协作。';r.optimizationSummary=['已补充对接运营团队'];r.optimizedProfile='具有1年经验';const safe=c.safeguard(r,sample.resumeText);assert.equal(safe.optimizedExperiences[0].optimized,safe.optimizedExperiences[0].original);assert.doesNotMatch(safe.fullOptimizedResume,/运营团队|跨部门|主导|1年/);assert.doesNotMatch(safe.optimizationSummary.join(''),/已补充对接/);});

test('仅返回优化条目时恢复原始日期公司职位标题，而不误报编造',()=>{const r=result();r.optimizedExperiences[0].original='2021.01-2024.01 星河测试企业 数据分析师\n使用 SQL、Excel 制作销售报表。负责零售行业数据整理。';const safe=c.safeguard(r,sample.resumeText);assert.match(safe.optimizedExperiences[0].optimized,/2021.01-2024.01 星河测试企业 数据分析师/);assert.match(safe.optimizedExperiences[0].optimized,/负责零售行业数据整理，使用 SQL、Excel/);assert.match(safe.fullOptimizedResume,/测试大学/);});
