const {test}=require('node:test'),assert=require('node:assert/strict');const core=require('../js/job-core.js');const registry=require('../js/source-registry.js');
const preferences={role:'数据分析师',city:'上海',exclude:'不考虑销售'};
const state={positionList:[{name:'数据分析师',companyName:'测试企业',workCity:'上海',positionURL:'https://www.zhaopin.com/jobdetail/CCUNITJ1.htm',salary60:'未公开',workingExp:'3年',education:'本科',jobDetailData:{position:{desc:{description:'SQL数据分析'}}}}]};
test('智联只解析公开JSON，不执行script；拒绝验证码及未知城市，不猜URL',async()=>{const adapter=await import('../sources/adapters/zhaopin.mjs');const source=registry.sources.find(s=>s.key==='zhaopin');assert.match(adapter.build(source,preferences),/jl538\/kw/);assert.match(adapter.build(source,{role:'产品经理',city:'深圳'}),/jl765/);assert.throws(()=>adapter.build(source,{city:'未知城市'}));const jobs=adapter.parse(source,'<script>__INITIAL_STATE__='+JSON.stringify(state)+';</script>');assert.equal(jobs[0].url,state.positionList[0].positionURL);assert.equal(jobs[0].salary,'未公开');assert.equal(jobs[0].sourceType,'job_board');assert.throws(()=>adapter.parse(source,'<script>__INITIAL_STATE__={"isVerification":true};</script>'));assert.throws(()=>adapter.parse(source,'<script>__INITIAL_STATE__=alert("x");</script>'));});
test('公司JSON-LD只接受真实URL；过期/无URL剔除，HTML数据不会执行',async()=>{const generic=await import('../sources/adapters/generic-career.mjs');const source={key:'company',name:'测试官网',type:'company_career',company:'测试公司',jobHosts:['company.invalid']};const posting={"@type":"JobPosting",title:'数据分析师',hiringOrganization:{name:'测试公司'},jobLocation:{address:{addressLocality:'上海'}},description:'SQL',url:'https://company.invalid/job/1'};const html=p=>'<script type="application/ld+json">'+JSON.stringify({'@graph':[p]})+'</script>';assert.equal(generic.parseStructured(source,html(posting)).length,1);assert.equal(generic.parseStructured(source,html({...posting,url:null})).length,0);assert.equal(generic.parseStructured(source,html({...posting,validThrough:'2020-01-01'})).length,0);assert.equal(generic.parseStructured(source,html({...posting,url:'https://evil.invalid/job'})).length,0);});
test('去重优先公司ATS、销售数据运营不误杀、明确美国远程不当上海',()=>{const base={id:'1',company:'测试公司',title:'数据分析师',location:'上海',url:'https://company.invalid/job/1',sourceType:'job_board',description:'SQL',workMode:'未公开'};assert.equal(core.shortlist([base,{...base,id:'2',sourceType:'ats',url:'https://ats.invalid/job/2'}],preferences,{},20)[0].sourceType,'ats');assert.equal(core.shortlist([{...base,title:'销售数据运营'}],{city:'上海',exclude:'销售'},{}).length,1);assert.equal(core.shortlist([{...base,location:'Remote US',workMode:'远程办公'}],preferences,{}).length,0);assert.equal(core.shortlist([{...base,location:'San Francisco',workMode:'混合办公'}],preferences,{}).length,0);});
test('来源失败隔离、公开缓存复用、不发密钥/简历、不调用MCP、上限24',async()=>{const {collectPublicJobs}=await import('../sources/service.mjs');const source={...registry.sources.find(s=>s.key==='zhaopin'),enabled:true,status:'working'};let calls=0;const fetcher=async(url,opts)=>{calls++;assert.ok(!url.includes('dashscope'));assert.equal(opts.headers.Authorization,undefined);assert.equal(opts.body,undefined);return new Response('<script>__INITIAL_STATE__='+JSON.stringify(state)+';</script>');};const a=await collectPublicJobs(preferences,{fetcher,cache:null,registry:[{...source,key:'test-cache'}]});const b=await collectPublicJobs(preferences,{fetcher,cache:null,registry:[{...source,key:'test-cache'}]});assert.equal(a.jobs.length,1);assert.equal(b.cacheHits,1);assert.equal(calls,1);const lots=Array.from({length:30},(_,i)=>({...source,key:'bad-'+i}));const c=await collectPublicJobs(preferences,{fetcher:async()=>new Response('denied',{status:403}),cache:null,registry:lots});assert.equal(c.requestCount,24);assert.equal(c.jobs.length,0);assert.ok(c.sourceReports.every(r=>r.status==='blocked'));});

test('公司官网只读取公开声明的同站sitemap；已登记ATS才可转交',async()=>{const generic=await import('../sources/adapters/generic-career.mjs');const source={key:'generic-map',name:'测试官网',type:'company_career',company:'测试公司',careerUrl:'https://company.invalid/careers',jobHosts:['company.invalid']};const seen=[];const payload={'@type':'JobPosting',title:'数据分析师',url:'https://company.invalid/jobs/1',description:'SQL',jobLocation:{address:{addressLocality:'上海'}}};const jobs=await generic.parse(source,'<h1>加入我们</h1>',{canRequest:()=>true,note(){},read:async url=>{seen.push(url);return url.endsWith('robots.txt')?'Sitemap: https://company.invalid/public.xml':url.endsWith('public.xml')?'<urlset><url><loc>https://company.invalid/jobs/1</loc></url></urlset>':'<script type="application/ld+json">'+JSON.stringify(payload)+'</script>';}});assert.equal(jobs.length,1);assert.equal(seen.length,3);const links=generic.discovery('<a href="https://jobs.lever.co/registered">Careers</a>','https://company.invalid/careers');assert.equal(links[0].adapter,'lever');});

test('Cloudflare缓存操作也纳入48次总额，避免免费Worker子请求超限',async()=>{const {collectPublicJobs}=await import('../sources/service.mjs');const source={...registry.sources.find(s=>s.key==='zhaopin'),enabled:true,status:'working'};let operations=0;const cache={async match(){operations++;return null;},async put(){operations++;}};const result=await collectPublicJobs(preferences,{cache,registry:Array.from({length:30},(_,i)=>({...source,key:'cache-budget-'+i})),fetcher:async()=>{operations++;return new Response('<script>__INITIAL_STATE__='+JSON.stringify(state)+';</script>');}});assert.ok(operations<=48);assert.equal(result.publicOperations,operations);assert.ok(result.requestCount<=24);assert.ok(result.jobs.length>0);});
