const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');require('../js/optimization-contract.js');const report=require('../js/report-print.js'),fixture=require('./fixtures/pdf-report.cjs');
test('整份报告包含所有结果及完整简历，而不是仅打印简历；所有折叠条目完整',()=>{const r=fixture(),before=JSON.stringify(r),html=report.render(r,'用户运营',new Date(2026,9,6,12,30));for(const label of ['AI 简历优化报告','JD 核心需求','已匹配优势','主要差距','本次优化重点','个人简介优化','工作经历优化','项目经历优化','建议重点展示的真实技能','需要补充 / 确认的信息','建议进一步补充的问题','完整优化版简历','建议确认真实性','2026-10-06'])assert.ok(html.includes(label));for(const s of [...r.matchedStrengths,...r.suggestedQuestions,...r.optimizedExperiences.flatMap(v=>[v.original,v.optimized,v.reason])])assert.ok(html.includes(s));assert.ok(html.replace(/<[^>]*>/g,'').includes(r.fullOptimizedResume));assert.equal(JSON.stringify(r),before);assert.doesNotMatch(html,/<(?:button|input|textarea|details|summary|script)\b/);});
test('空项目不显示、无简介不伪造；文字全部转义，恶意HTML不执行',()=>{const r=fixture();r.optimizedProjects=[];r.optimizedProfile=globalThis.OptimizationContract.fallback;r.jdSummary='<img src=x onerror=alert(1)>';const html=report.render(r,'<script>unsafe</script>');assert.ok(!html.includes('项目经历优化'));assert.ok(!html.includes('个人简介优化'));assert.doesNotMatch(html,/<img|<script/);assert.match(html,/&lt;img/);});
test('建议不混进最后正式简历，PDF仅使用现有全文',()=>{const html=report.render(fixture(),'用户运营');const tail=html.slice(html.indexOf('<section class="report-section report-full-resume"'));assert.ok(tail.includes('完整优化简历最后一行'));assert.ok(!tail.includes('如有真实数据'));assert.ok(!tail.includes('是否有可以验证'));});
test('A4自然分页无滚动裁剪；较短卡片整块保留、超长卡片允许跨页',()=>{const html=report.render(fixture(),'运营'),css=fs.readFileSync('print-report.css','utf8');assert.match(css,/size:A4 portrait/);assert.match(css,/body > :not\(#pdf-report\)/);assert.match(css,/max-height:none!important/);assert.match(css,/overflow:visible!important/);assert.match(css,/break-after:avoid-page/);assert.match(css,/\.report-comparison-long \{ break-inside:auto/);assert.match(html,/report-comparison-long/);});
function environment(){const events={},nodes=new Map(),button={disabled:false};const win={document:{title:'原网页标题',body:{append(node){nodes.set(node.id,node);}},getElementById(id){return nodes.get(id);},createElement(){return {innerHTML:'',setAttribute(){},replaceChildren(){this.innerHTML='';}};},querySelectorAll(){return [button];}},addEventListener(name,fn){events[name]=fn;},matchMedia(){return {addEventListener(){}};},printCalls:0,print(){this.printCalls++;}};return {win,events,nodes,button};}
test('无结果不能打印；成功导出只调用原生print，重复点击阻止，关闭后恢复标题和按钮',()=>{const {win,events,nodes,button}=environment(),api=report.install(win);assert.equal(api.print(),false);assert.equal(win.printCalls,0);api.set(fixture(),'运营',new Date(2026,9,6));const html=nodes.get('pdf-report').innerHTML;assert.equal(api.print(),true);assert.equal(api.print(),false);assert.equal(win.printCalls,1);assert.match(win.document.title,/AI简历优化报告_运营_2026-10-06/);assert.equal(button.disabled,true);events.afterprint();assert.equal(win.document.title,'原网页标题');assert.equal(button.disabled,false);assert.equal(nodes.get('pdf-report').innerHTML,html);api.clear();assert.equal(nodes.get('pdf-report').innerHTML,'');assert.equal(api.print(),false);});
test('打印异常安全恢复，手动打印使用同一报告，文件名去除联系方式和路径符号',()=>{const {win,events}=environment(),api=report.install(win);api.set(fixture(),'运营');events.beforeprint();events.afterprint();assert.equal(win.document.title,'原网页标题');win.print=()=>{throw new Error('unsupported');};assert.equal(api.print(),false);assert.equal(win.document.title,'原网页标题');assert.doesNotMatch(report.title('运营13800138000 user@example.com /:?',new Date(2026,9,6)),/13800138000|example|[:/?]/);});
test('正常成功区才有下载按钮、清空和重新优化撤回旧报告、无网络/AI/持久化依赖',()=>{const app=fs.readFileSync('js/app.js','utf8'),html=fs.readFileSync('index.html','utf8'),script=fs.readFileSync('js/report-print.js','utf8');assert.match(app,/ResumeReport.set\(result,role\)/);assert.match(app,/download-pdf-report/);assert.match(app,/state.optimization=null;window.ResumeReport.clear/);assert.doesNotMatch(html,/download-pdf-report/);assert.doesNotMatch(script,/fetch\(|XMLHttpRequest|localStorage|sessionStorage|indexedDB|ResumeOptimization|API_KEY/);});

test('超长经历使用重复表头保留公司与原文/优化后上下文',()=>{const html=report.render(fixture(),'用户运营'),css=fs.readFileSync('print-report.css','utf8');assert.match(html,/<table class="report-long-copy"><thead>/);assert.match(html,/合成测试公司C · 用户运营 <span>· 原文/);assert.match(css,/display:table-header-group/);});

test('没有afterprint事件的浏览器在返回页面焦点时仍恢复按钮和原标题',()=>{const {win,events,button}=environment(),api=report.install(win);api.set(fixture(),'运营');api.print();assert.equal(button.disabled,true);events.focus();assert.equal(button.disabled,false);assert.equal(win.document.title,'原网页标题');});

test('完整版不强制另起一页，标题和简短说明与正文连接',()=>{const css=fs.readFileSync('print-report.css','utf8');assert.match(css,/\.report-full-resume \{ break-before:auto; page-break-before:auto/);assert.doesNotMatch(css,/break-before:page|page-break-before:always/);assert.match(css,/\.report-caption \{ break-after:avoid-page/);});
test('导出提示只在第一次有效点击显示且先于print，不创建持久存储',()=>{const {win,events}=environment(),sequence=[];win.alert=msg=>sequence.push(msg);win.print=()=>{sequence.push('print');};const api=report.install(win);api.print();assert.equal(sequence.length,0);api.set(fixture(),'用户运营');api.print();events.afterprint();api.print();events.afterprint();assert.deepEqual(sequence,[report.printTip,'print','print']);assert.match(sequence[0],/关闭“页眉和页脚”/);assert.equal(win.document.title,'原网页标题');});
test('真实性占位只进入独立提醒区，显示层不修改原始AI结果，重复转换稳定',()=>{const r=fixture(),notice='该项优势表达建议确认真实性，请对照原简历核实。';r.matchedStrengths.push(notice);r.jdSummary+='\n'+notice;r.optimizedExperiences[0].optimized+=notice;r.fullOptimizedResume+='\n'+notice;const raw=JSON.stringify(r),display=report.presentation(r);assert.equal(JSON.stringify(r),raw);assert.ok(!display.matchedStrengths.includes(notice));assert.ok(!display.jdSummary.includes(notice));assert.ok(!display.optimizedExperiences[0].optimized.includes(notice));assert.ok(!display.fullOptimizedResume.includes(notice));assert.ok(display.verificationNotes.includes(notice));assert.deepEqual(report.presentation(display),display);const html=report.render(r,'用户运营'),warning=html.indexOf('<h2>建议确认真实性</h2>'),full=html.indexOf('<h2>完整优化版简历</h2>');assert.equal(html.indexOf(notice),html.lastIndexOf(notice));assert.ok(html.indexOf(notice)>warning&&html.indexOf(notice)<full);});

test('浏览器安装接口暴露显示层转换，成功结果渲染不受影响',()=>{const api=report.install(environment().win);assert.equal(api.presentation,report.presentation);assert.equal(api.presentation(fixture()).matchScore,72);});
