
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const core=require('../js/job-core.js');const web=require('../js/websearch-core.js');const contract=require('../js/analysis-contract.js');const {analysis}=require('./analysis-sample.cjs');
function budget(){let used=0;return {idFromName:n=>n,get:()=>({fetch:async url=>{if(url.endsWith('/reserve'))used++;return new Response(JSON.stringify({allowed:true,used,limit:1500,remaining:1500-used,paused:used>=1500}));}})};}
const p={role:'数据分析师',city:'上海',industry:'互联网',exclude:'不考虑销售'};
const urls=['https://www.zhipin.com/job_detail/unit-test.html','https://www.liepin.com/job/12345678.shtml','https://www.zhaopin.com/jobdetail/CCUNITTESTJ123.htm'];
const row=(url=urls[0])=>({title:'数据分析师',url,company:'测试公司（仅测试）',city:'上海',summary:'公开摘要：SQL 数据分析职责。'});
function mockMcp({errorDomain='',sse=false}={}){let methods=[];const fetcher=async(url,opts)=>{assert.equal(url,'https://dashscope.aliyuncs.com/api/v1/mcps/WebSearch/mcp');assert.equal(opts.redirect,'manual');assert.equal(opts.headers.Authorization,'Bearer unit-test-not-real');const b=JSON.parse(opts.body);methods.push(b.method);assert.equal(b.tools,undefined);assert.doesNotMatch(opts.body,/candidateProfile|educationSummary|resumeText/);if(b.method==='notifications/initialized')return new Response(null,{status:202});let result;if(b.method==='initialize')result={protocolVersion:'2025-03-26',capabilities:{},serverInfo:{name:'test-only',version:'1'}};else{assert.equal(opts.headers['Mcp-Session-Id'],'unit-test-session');if(b.method==='tools/list')result={tools:[{name:'bailian_web_search',inputSchema:{type:'object',required:['query'],properties:{query:{type:'string'}}}}]};else{const domain=web.platforms.find(x=>b.params.arguments.query.includes('site:'+x.domain))?.domain;assert.ok(domain);if(domain===errorDomain)throw new TypeError('test network error');const i=web.platforms.findIndex(x=>x.domain===domain);result={content:[{type:'text',text:JSON.stringify({results:[row(urls[i]),row(urls[i]),row('https://evil.invalid/job/1'),{title:'无链接'}]})}]};}}
 const frame={jsonrpc:'2.0',id:b.id,result};return new Response(sse?'event: message\ndata: '+JSON.stringify(frame)+'\n\n':JSON.stringify(frame),{headers:{'Content-Type':sse?'text/event-stream':'application/json','Mcp-Session-Id':'unit-test-session'}});};return {fetcher,methods};}

test('缺少持久计数器时即使启用搜索也禁止上游调用',async()=>{const {searchPublicJobs}=await import('../ai/websearch.mjs');for(const env of [{},{AI_API_KEY:'unit-test-not-real',WEBSEARCH_ENABLED:'true'},{AI_API_KEY:'unit-test-not-real',WEBSEARCH_ENABLED:'true',FREE_MODE:'true'}]){const r=await searchPublicJobs(p,env,()=>{assert.fail('must not make a search request');});assert.equal(r.searchCalls,0);assert.equal(r.jobs.length,0);assert.equal(r.status,'FREE_SEARCH_UNAVAILABLE');}});

test('官方 Streamable HTTP 初始化/会话/工具发现；三个平台各一次，不调用模型',async()=>{const {searchPublicJobs}=await import('../ai/websearch.mjs');for(const sse of [false,true]){const mock=mockMcp({sse});const r=await searchPublicJobs(p,{AI_API_KEY:'unit-test-not-real',WEBSEARCH_ENABLED:'true',FREE_MODE:'true',SEARCH_BUDGET:budget()},mock.fetcher);assert.equal(r.searchCalls,3);assert.equal(r.jobs.length,3);assert.equal(mock.methods.filter(x=>x==='tools/call').length,3);assert.deepEqual(r.jobs.map(j=>j.source),web.platforms.map(s=>s.source));}});

test('失败不重复搜索，继续其他平台，单请求工具调用上限3',async()=>{const {searchPublicJobs,WebSearchClient}=await import('../ai/websearch.mjs');const mock=mockMcp({errorDomain:'liepin.com'});const r=await searchPublicJobs(p,{AI_API_KEY:'unit-test-not-real',WEBSEARCH_ENABLED:'true',FREE_MODE:'true',SEARCH_BUDGET:budget()},mock.fetcher);assert.equal(r.searchCalls,3);assert.equal(r.jobs.length,2);assert.equal(mock.methods.filter(x=>x==='tools/call').length,3);const client=new WebSearchClient('unit-test-not-real',mock.fetcher,async()=>({allowed:true}));await client.connect();await client.search(web.queries(p)[0]);await assert.rejects(client.search(web.queries(p)[0]),{code:'SEARCH_LIMIT'});});

test('动态关键词不是固定城市；原URL保留，域名及职位路径校验，无字段不猜',()=>{assert.match(web.queries(p)[0].query,/site:zhipin.com 数据分析师 上海 互联网 招聘/);assert.match(web.queries({role:'产品经理',city:'深圳'})[2].query,/产品经理 深圳/);const r=web.normalizeResults({results:[{title:'数据分析师招聘',url:urls[0],snippet:'公开摘要'},row('https://zhipin.com.evil.invalid/job_detail/1.html'),row('https://www.zhipin.com/zhaopin/category')]},'zhipin.com');assert.equal(r.length,1);assert.equal(r[0].url,urls[0]);for(const k of ['company','city','salary','experience','education','publishedAt'])assert.equal(r[0][k],'未公开');assert.equal(web.normalizeResults({results:[row(urls[1])]},'zhipin.com').length,0);});

test('筛选保留销售数据分析师，过滤电话销售；真实异地过滤，未知城市降低确信',()=>{const base=web.normalizeResults({results:[row()]},'zhipin.com')[0];const jobs=[base,{...base,id:'sales-data',url:urls[0]+'?n=2',title:'销售数据分析师'},{...base,id:'sales',url:urls[0]+'?n=3',title:'电话销售'},{...base,id:'beijing',url:urls[0]+'?n=4',location:'北京'},{...base,id:'unknown',url:urls[0]+'?n=5',location:'未公开'}];const result=core.shortlist(jobs,p,analysis,15);assert.deepEqual(new Set(result.map(j=>j.id)),new Set([base.id,'sales-data','unknown']));assert.equal(result.at(-1).id,'unknown');});

test('国内真实域名进入匹配校验；schema包含confidence，短摘要强制低confidence',async()=>{const {matchingInput,matchJobs}=await import('../ai/job-matching.mjs');const jobs=web.normalizeResults({results:[row()]},'zhipin.com');const input=matchingInput({profile:analysis,preferences:p,jobs});let count=0;const result=await matchJobs(input,{AI_API_KEY:'unit-test-not-real',AI_BASE_URL:'https://unit-test.cn-beijing.maas.aliyuncs.com/compatible-mode/v1'},async(url,opts)=>{count++;const b=JSON.parse(opts.body);assert.equal(b.model,'qwen3.8-flash');assert.equal(b.enable_thinking,false);assert.equal(b.enable_search,undefined);assert.ok(b.response_format.json_schema.schema.properties.matches.items.required.includes('confidence'));return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({matches:[{id:jobs[0].id,matchScore:80,matchReasons:['已有SQL'],gaps:['摘要不完整'],recommendation:'核对原岗位',resumeTips:[],confidence:'高'}]})}}]}));});assert.equal(count,1);assert.equal(result.matches[0].confidence,'低');let failures=0;await assert.rejects(matchJobs(input,{AI_API_KEY:'unit-test-not-real',AI_BASE_URL:'https://unit-test.cn-beijing.maas.aliyuncs.com/compatible-mode/v1'},()=>{failures++;throw new TypeError('network');}));assert.equal(failures,1);});

test('前端完整流程一次搜索接口＋一次批量匹配，无逐岗位抓取或AI请求',async()=>{const root={JobMatcherProviders:{},JobCore:core,WebSearchCore:web,AnalysisContract:contract,JobSources:[],AnalysisConfig:{endpoint:'https://worker.invalid/api/resume/analyze'}};const calls=[];vm.runInNewContext(fs.readFileSync('js/jobs-provider.js','utf8'),{window:root,AbortController,setTimeout,clearTimeout,TextDecoder,console:{warn(){}},fetch:async(url,opts)=>{calls.push(url);if(url.endsWith('/search')){assert.deepEqual(Object.keys(JSON.parse(opts.body)),['preferences']);return new Response(JSON.stringify({mode:'live',jobs:web.normalizeResults({results:[row()]},'zhipin.com'),searchCalls:3,usage:{used:3,limit:1500,remaining:1497,paused:false},status:'OK',warnings:[]}));}assert.ok(url.endsWith('/match'));const input=JSON.parse(opts.body);assert.equal(input.jobs.length,1);return new Response(JSON.stringify({mode:'live',matches:[{id:input.jobs[0].id,matchScore:75,matchReasons:[],gaps:[],recommendation:'核对',resumeTips:[],confidence:'低'}]}));}});const result=await root.JobMatcherProviders.jobProvider.search(p,analysis);assert.equal(calls.length,2);assert.equal(result.searchCalls,3);assert.equal(result.usage.used,3);assert.equal(result.usage.limit,1500);assert.equal(result.jobs[0].isMock,false);assert.equal(result.jobs[0].matchScore,75);});

test('Worker搜索输入不接受简历；FREE_MODE不触发上游，OPTIONS保持CORS',async()=>{const {handleJobs}=await import('../ai/jobs-handler.mjs');const env={ALLOWED_ORIGINS:'http://127.0.0.1:4173',FREE_MODE:'true'};const req=body=>new Request('https://worker.invalid/api/jobs/search',{method:'POST',headers:{Origin:'http://127.0.0.1:4173','Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal((await handleJobs(req({resumeText:'do not send',preferences:p}),env)).status,400);const r=await handleJobs(req({preferences:p}),env,{},()=>assert.fail('zero upstream calls'));assert.equal(r.status,200);assert.equal((await r.json()).searchCalls,0);});

test('MCP transport 必须裸调用，不能把 Worker 原生fetch绑定到客户端对象',async()=>{const {WebSearchClient}=await import('../ai/websearch.mjs');let called=0;async function nativeLike(url,options){'use strict';assert.equal(this,undefined);called++;const request=JSON.parse(options.body);return new Response(JSON.stringify({jsonrpc:'2.0',id:request.id,result:{protocolVersion:'2025-03-26'}}));}const client=new WebSearchClient('unit-test-not-real',nativeLike);await client.rpc('initialize',{});assert.equal(called,1);});

 test('嵌套及JSON字符串搜索结果不因未预设外层字段名而被静默丢弃',()=>{for(const payload of [{result:{search_result:[row()]}},{webPages:{value:[row()]}},{payload:JSON.stringify({pages:[row()]})}])assert.equal(web.normalizeResults(payload,'zhipin.com').length,1);const r=web.normalizeResults({pages:[{title:'数据分析师',url:urls[0],summary:'工作地点： 上海，公司： 测试企业（仅测试）'}]},'zhipin.com');assert.equal(r[0].city,'上海');assert.equal(r[0].company,'测试企业（仅测试）');assert.deepEqual(web.normalizeResults({message:'没有结果'},'zhipin.com'),[]);});
