import '../js/source-registry.js';import '../js/job-core.js';
import * as zhaopin from './adapters/zhaopin.mjs';import * as greenhouse from './adapters/greenhouse.mjs';import * as lever from './adapters/lever.mjs';import * as ashby from './adapters/ashby.mjs';import * as smartrecruiters from './adapters/smartrecruiters.mjs';import * as generic from './adapters/generic-career.mjs';
const adapters={zhaopin,greenhouse,lever,ashby,smartrecruiters,'generic-career':generic};const core=globalThis.JobCore;const memory=new Map();
export const LIMITS=Object.freeze({requests:24,concurrency:3,timeout:9000,cacheSeconds:2700,candidates:50});
export async function collectPublicJobs(preferences,{fetcher=fetch,cache=globalThis.caches?.default,registry=globalThis.PublicSources}={}){
 let requestCount=0,cacheHits=0,operations=0;const reserveOperation=()=>{if(operations>=48)throw Error("REQUEST_BUDGET");operations++;};const reports=[],all=[];const fetchText=async(url)=>{if(requestCount>=LIMITS.requests)throw Error('REQUEST_BUDGET');reserveOperation();requestCount++;const transport=fetcher;const r=await transport(url,{method:'GET',headers:{Accept:'application/json,text/html'},redirect:'manual',signal:AbortSignal.timeout(LIMITS.timeout)});if(!r.ok)throw Error([401,403,429].includes(r.status)?'ACCESS_LIMIT':'HTTP_'+r.status);const reader=r.body?.getReader();if(!reader)throw Error('SOURCE_EMPTY');let size=0,out='';const decoder=new TextDecoder();try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>20000000){await reader.cancel();throw Error('SOURCE_TOO_LARGE');}out+=decoder.decode(value,{stream:true});}}finally{reader.releaseLock();}out+=decoder.decode();if(/<title[^>]*>[^<]*(?:验证码|安全验证|Just a moment|Access Denied)|captcha-container|antibot\/verifycode|验证后继续访问|verify you are human/i.test(out))throw Error('ACCESS_LIMIT');return out;};
 async function run(source){const report={key:source.key,name:source.name,company:source.company||'',type:source.type,status:'working',count:0};reports.push(report);try{const adapter=adapters[source.adapter];if(!adapter)throw Error('ADAPTER_UNAVAILABLE');const url=adapter.build(source,preferences);const key=new Request('https://public-jobs-cache.invalid/'+source.key+'?url='+encodeURIComponent(url)+'&role='+encodeURIComponent(preferences.role||'')+'&city='+encodeURIComponent(preferences.city||''));let jobs;let cached=null;try{if(cache&&operations<48){reserveOperation();cached=await cache.match(key);}}catch{}const saved=memory.get(key.url);if(cached){jobs=await cached.json();cacheHits++;}else if(saved&&saved.until>Date.now()){jobs=saved.jobs;cacheHits++;}else{const html=await fetchText(url);const context={read:fetchText,canRequest:()=>requestCount<LIMITS.requests&&operations<48,note:()=>report.partial=true,relevant:j=>core.shortlist([j],{role:preferences.role,city:preferences.city},{},1).length>0};context.delegate=async link=>{const linked=registry.find(s=>s.enabled&&s.status==='working'&&s.type==='ats'&&s.careerUrl&&(link.url===s.careerUrl||link.url.startsWith(s.careerUrl.replace(/\/$/,'')+'/')));if(!linked||!adapters[linked.adapter])return [];const selected=adapters[linked.adapter];return selected.parse(linked,await fetchText(selected.build(linked,preferences)),context);};jobs=await adapter.parse(source,html,context);if(!Array.isArray(jobs))throw Error('SOURCE_FORMAT');jobs=jobs.filter(j=>context.relevant(j)).slice(0,LIMITS.candidates);if(cache&&jobs.length&&operations<48){try{reserveOperation();await cache.put(key,new Response(JSON.stringify(jobs),{headers:{'Content-Type':'application/json','Cache-Control':'public, max-age='+LIMITS.cacheSeconds}}));}catch{report.cacheUnavailable=true;}}else{if(memory.size>=100)memory.delete(memory.keys().next().value);memory.set(key.url,{until:Date.now()+LIMITS.cacheSeconds*1000,jobs});}}report.count=jobs.length;all.push(...jobs);}catch(e){report.status=e.message==='ACCESS_LIMIT'?'blocked':'limited';report.error=/^(?:ACCESS_LIMIT|HTTP_\d+|SOURCE_\w+|CITY_NOT_SUPPORTED|ADAPTER_UNAVAILABLE|PUBLIC_DATA_MISSING|REQUEST_BUDGET)$/.test(e.message)?e.message:e.name==='TimeoutError'?'SOURCE_TIMEOUT':'SOURCE_NETWORK';}}
 const active=registry.filter(s=>s.enabled&&s.status==='working').sort((a,b)=>a.priority-b.priority||(a.key==='sia'?-1:b.key==='sia'?1:0));
 for(const priority of [1,2,3]){const tier=active.filter(s=>s.priority===priority);for(let i=0;i<tier.length;i+=LIMITS.concurrency){if(requestCount>=LIMITS.requests||operations>=48||core.shortlist(all,preferences,{},LIMITS.candidates).length>=35)break;await Promise.all(tier.slice(i,i+LIMITS.concurrency).map(run));}}
 const jobs=core.shortlist(all,preferences,{},LIMITS.candidates);return {mode:'live',jobs,total:all.length,requestCount,requestLimit:LIMITS.requests,publicOperations:operations,operationLimit:48,cacheHits,sourceReports:reports,availableSources:reports.filter(r=>r.status==='working').length,searchCalls:0,warnings:reports.filter(r=>r.status!=='working').map(r=>(r.company||r.name)+' 暂不可公开读取，已继续其他来源。')};
}
